arb-dir: lib/l10n/app
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
nullable-getter: false
preferred-supported-locales:
  - en
  - es
  - pt
  - fr
  - de
  - ar
  - hi
  - ja
  - ru
  - zh